#
# Build's docs and publishes to Gitlab pages
# 

image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - echo %PATH%
  - python -V  # Print out python version for debugging

pages:
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs ; ./make.bat html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
