########################################################################################################################
# Repo tool base settings
########################################################################################################################

[repo]
# Repository Name
name = "warp"

########################################################################################################################
# Build tool setup
########################################################################################################################

[repo_build]

# List of packman projects to pull (in order)
fetch.packman_host_files_to_pull = [
    "${root}/deps/host-deps.packman.xml",
]

fetch.packman_target_files_to_pull = [
    "${root}/deps/target-deps.packman.xml",
]

# Extensions precache
fetch.after_pull_commands = [
]
