
[package]
# Semantic Versioning is used: https://semver.org/
version = "0.1.25"
authors = ["Miles Macklin"]
title = "Warp"
description="Python DSL for high performance graphics and simulation"
readme  = "docs/README.md"
repository="https://gitlab-master.nvidia.com/mmacklin/warp"
category = "graph"
keywords = ["kit", "omnigraph", "warp", "simulation"]
changelog="docs/CHANGELOG.md"

preview_image = "data/preview.png"
icon = "data/icon.png"

# Watch the .ogn files for hot reloading (only works for Python files)
[fswatcher.patterns]
include = ["*.ogn", "*.py"]
exclude = ["Ogn*Database.py", "*/ogn*"]

[dependencies]
"omni.kit.test" = {}
"omni.graph.core" = {}
"omni.graph" = {}

# Main python module this extension provides, it will be publicly available as "import omni.warp".
[[python.module]]
name = "omni.warp"

# Additional python module with tests, to make them discoverable by test system.
[[python.module]]
name = "omni.warp.ogn.tests"

# Core language module
[[python.module]]
name = "warp"
path = "."
public = true